version: "3.8"

volumes:
  kcalc-postgres:
    driver: local
  keycloak-postgres:
    driver: local

services:
  kcalc-postgres:
    image: postgres:16
    restart: always
    container_name: kcalc-postgres
    environment:
      POSTGRES_USER: kcalc
      POSTGRES_PASSWORD: kcalc
    ports:
      - '5522:5432'
    volumes:
      - kcalc-postgres:/var/lib/postgresql/data

  keycloak-postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    volumes:
      - keycloak-postgres:/var/lib/postgresql/data
  keycloak-kcalc:
    image: quay.io/keycloak/keycloak:22.0.5
    command: "start-dev"
    container_name: keycloak-kcalc
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the PostgreSQL JDBC driver documentation in order to use it.
    #      JDBC_PARAMS: "ssl=true"
    ports:
      - "8443:8080"
    depends_on:
      - keycloak-postgres
    healthcheck:
      test: "curl -f http://localhost:8080/admin || exit 1"
