version: "3.8"

volumes:
  db:
    driver: local

services:
  kcalc-postgres:
    image: postgres:16
    restart: always
    container_name: kcalc-postgres
    environment:
      POSTGRES_USER: kcalc
      POSTGRES_PASSWORD: kcalc
    ports:
      - '5522:5432'
    volumes:
      - db:/var/lib/postgresql/data
