spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8443/realms/kcalc-realm
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
  datasource:
    url: jdbc:postgresql://localhost:5432/kcalc
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
    hikari:
      schema: kcalc
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true

server:
  port: 8082

logging:
  level:
    org.springframework.security: DEBUG
    org.hibernate.sql: debug
    org.hibernate.descriptor.sql.BasicBinder: TRACE

keycloak:
  serverUrl: http://localhost:8443
  realmName: kcalc-realm
  clientId: kcalc-keycloak-client
  redirectUrl: http://localhost:3000/*
  adminUsername: admin
  adminPassword: admin

security:
  cors:
    allowed-origins: http://localhost:3000